name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Build documentation
        run: |
          cd docs
          poetry run make html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
